# Generated by Django 5.2.1 on 2025-05-16 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('type_animal', models.CharField(choices=[('chat', 'Chat'), ('chien', 'Chien'), ('lapin', 'Lapin')], max_length=10)),
                ('race', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('poids', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='owners.owner')),
            ],
        ),
    ]
